# Generated by Django 5.1.2 on 2024-10-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['created_at'], name='myapp2_vide_created_3113f1_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['user'], name='myapp2_vide_user_id_2c77e0_idx'),
        ),
    ]
